linux-libc-headers: fix building failure of turbostat after uprev kernel v4.18.37
Issue: LIN1018-4113

Yocto kernel v4.18.37 integrates a upstream commit

8bd9cb51daa(locking/atomics, asm-generic: Move some macros from <linux/bitops.h> to a new <linux/bits.h> file)

which introduces a new header file bits.h. The turbostat is built outside of kernel tree, so we need to install
the bits.h to receipe sysroot.

The build failure without exporting the file

In file included from turbostat.c:23:
msr-index.h:5:10: fatal error: linux/bits.h: No such file or directory
 #include <linux/bits.h>
          ^~~~~~~~~~~~~~

Signed-off-by: Yue Tao <Yue.Tao@windriver.com>