openssl: fix multilib file install conflicts
Issue: LIN1018-3420

To avoid issue like below if run "bitbake lib32-core-image-minimal" with
series userspace packages(LAMP,krb5...) added:

Error: Transaction check error:
  file /usr/bin/c_rehash conflicts between attempted installs of
   lib32-openssl-bin-1.1.1-r0.armv7at2hf_neon and openssl-bin-1.1.1-r0.aarch64

(LOCAL REV: NOT UPSTREAM) -- Send to oe-core later

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>