Revert "image_types: use cpio-native to build cpio images"
Issue: LIN1018-3613

Commit a75eba71145efa1c3d206c5e5c00608a50f013bc forced introduced
cpio-native and trigger the below issue:
ERROR: wrlinux-image-glibc-std-1.0 do_bootimg: Error executing a python function
in exec_python_func() autogenerated:
File: 'oe-core/meta/classes/staging.bbclass', lineno: 151, function: staging_copyfile
0147: os.symlink(linkto, dest)
0148: #bb.warn(c)
0149: else:
0150: try:
*** 0151: os.link(c, dest)
0152: except OSError as err:
0153: if err.errno == errno.EXDEV:
0154: bb.utils.copyfile(c, dest)
0155: else:
Exception: FileExistsError: [Errno 17] File exists:
'<path>/sysroots-components/x86_64/cpio-native/sbin/rmt' -> '/recipe-sysroot-native/sbin/rmt'

Both cpio-native and tar-replacement-native provide '/sbin/rmt' for the
wrlinux-image-glibc-std which causes the confliction.
This is just workaround and a formal fix should be provided later.

This reverts commit a75eba71145efa1c3d206c5e5c00608a50f013bc.

Signed-off-by: Haiqing Bai <Haiqing.Bai@windriver.com>