nfs-utils: fix build error under tests folder
Issue: LIN1018-1676

* When enable the test as below in nfs-utils recipe,
  do_compile_append_class-target () {
        oe_runmake -C tests statdb_dump
        oe_runmake -C tests/nsm_client nsm_client
  }

  There comes some build error as:
  1,
  | make: *** No rule to make target '../support/nfs/libnfs.a', needed by 'statdb_dump'.  Stop.
  | make: *** No rule to make target '../../support/nfs/libnfs.a', needed by 'nsm_client'.  Stop.

  2,
  | ../support/nsm/libnsm.a(file.o): In function `nsm_make_pathname':
  | /usr/src/debug/nfs-utils/2.3.1-r0/nfs-utils-2.3.1/support/nsm/file.c:175: undefined reference to `generic_make_pathname'
  | /usr/src/debug/nfs-utils/2.3.1-r0/nfs-utils-2.3.1/support/nsm/file.c:175: undefined reference to `generic_make_pathname'
  | /usr/src/debug/nfs-utils/2.3.1-r0/nfs-utils-2.3.1/support/nsm/file.c:175: undefined reference to `generic_make_pathname'
  | ../support/nsm/libnsm.a(file.o): In function `nsm_setup_pathnames':
  | /usr/src/debug/nfs-utils/2.3.1-r0/nfs-utils-2.3.1/support/nsm/file.c:280: undefined reference to `generic_setup_basedir'
  | collect2: error: ld returned 1 exit status

* Redefine the reference path of libnfs.a to
 ../support/nfs/.libs/libnfs.a to fix the error 1 as
  above

* The function generic_make_pathname is introduced in
  nfs-utils 2.3.1
  Add the source file which defines function generic_make_pathname to
  libnsm_a_SOURCES of libnsm.a to fix the undefined reference
  error 2 as above

 (LOCAL REV: NOT UPSTREAM) -- Send to oe-core 20180713

Signed-off-by: Mingli Yu <Mingli.Yu@windriver.com>