cpio: Change the installation path of rmt to usr sbin dir
Issue: LIN1018-3618

Commit a75eba71145efa1c3d206c5e5c00608a50f013bc was reverted
temporarily to avoid the below issue:
ERROR: wrlinux-image-glibc-std-1.0 do_bootimg: Error executing a python function
in exec_python_func() autogenerated:
File: 'oe-core/meta/classes/staging.bbclass', lineno: 151, function: staging_copyfile
0147: os.symlink(linkto, dest)
0148: #bb.warn(c)
0149: else:
0150: try:
*** 0151: os.link(c, dest)
0152: except OSError as err:
0153: if err.errno == errno.EXDEV:
0154: bb.utils.copyfile(c, dest)
0155: else:
Exception: FileExistsError: [Errno 17] File exists:
'<path>/sysroots-components/x86_64/cpio-native/sbin/rmt' -> '/recipe-sysroot-native/sbin/rmt'

The reason is that feature ima depends on class ima-evm-rootfs which
depends on tar-replacement-native like:
ima-evm-rootfs.bbclass:do_image_tar[depends] += "tar-replacement-native:do_populate_sysroot"

But both cpio-native and tar-replacement-native provide '/sbin/rmt'. Now this
conflict is fixed by changing the binary 'rmt' to 'usr/sbin/rmt' in native sysroot.

(LOCAL REV: NOT UPSTREAM) -- pending

Signed-off-by: Haiqing Bai <Haiqing.Bai@windriver.com>